### ISSUE TITLE
Resource blocked by CORS policy

### ISSUE THREAD

**Issue by tripstar22** [tgreyuk/fpl-api-node#1]
Getting a response that `No 'Access-Control-Allow-Origin' header is present on the requested resource.` when I try to fetch elements. Using the module in an Angular CLI project. Here is my code and the error code I get when the application loads in the browser. Any help is appreciated, thanks!

```
import { Component, OnInit } from '@angular/core';
import * as fplapi from 'fpl-api-node';

@Component({
	selector: 'pl-stat-saves',
	templateUrl: './stat-saves.component.html',
	styleUrls: ['./stat-saves.component.scss']
})
export class StatSavesComponent implements OnInit {

	constructor() { }

	/**
	* Returns a promise that if fulfilled returns json object mapped to the given request
	* @param path The path of the rest web api request
	* @returns {Promise}
	* @private
	*/
	fetchData(path: string) {

 		return new Promise((resolve: any, reject: any) => {

			fetch(`https://fantasy.premierleague.com/drf/${path}`).then((res) => {
		  		return res.json();
			}).then((json) => {
		  		resolve(json);
			}).catch((err) => {
		  		reject(err);
			});
		});
	}

	/**
	* Elements (players):
	* A promise that if fulfilled returns an object
	* mapped to https://fantasy.premierleague.com/drf/elements
	* @returns {Promise}
	*/
	fetchElements(): Promise<Element[]> {
  		return this.fetchData('/elements');
	}

	ngOnInit() {
		this.fetchElements();
	}

}
```
Fetch API cannot load https://fantasy.premierleague.com/drf//elements. Redirect from 'https://fantasy.premierleague.com/drf//elements' to 'https://fantasy.premierleague.com/drf/elements/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by tripstar22** [comment]
Fixed by declaring `mode: 'no-cors'` when fetching data. Was looking for a better cross-browser solution but IE does not support `fetch` anyway according to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch). Still getting a 404 for url when trying to fetch data but I wanted to go ahead and update the status of the CORS issue. New code below... 

```
import { Component, OnInit } from '@angular/core';
import * as fplapi from 'fpl-api-node';

@Component({
	selector: 'pl-stat-saves',
	templateUrl: './stat-saves.component.html',
	styleUrls: ['./stat-saves.component.scss']
})
export class StatSavesComponent implements OnInit {

	constructor() { }

	/**
	* Returns a promise that if fulfilled returns json object mapped to the given request
	* @param path The path of the rest web api request
	* @returns {Promise}
	* @private
	*/
	fetchData(path: string) {

		let myMode = {
			mode: 'no-cors'
		}

 		return new Promise((resolve: any, reject: any) => {

			fetch('https://fantasy.premierleague.com/drf/elements', myMode).then((res) => {
				return res.json();
			}).then((json) => {
		  		resolve(json);
				console.log(json);
			}).catch((err) => {
		  		reject(err);
			});
		});
	}

	/**
	* Elements (players):
	* A promise that if fulfilled returns an object
	* mapped to https://fantasy.premierleague.com/drf/elements
	* @returns {Promise}
	*/
	fetchElements(): Promise<Element[]> {
  		return this.fetchData('elements');
	}

	ngOnInit() {
		this.fetchElements();
	}

}
```

**Comment by tgreyuk** [comment]
Hi.. I think in this instance you might be better off using a restful api in which case you do not need to worry about CORS at all. I have mocked up a simple example here https://github.com/tgreyuk/fpl-angular-cli-express-seed

You would fetch data using express route as follows:

```
const fplapi = require('fpl-api-node');

// Fetch all teams all teams
router.get('/elements', (req, res) => {

  fplapi.fetchElements().then((data) => {

    // do something with our data 
     res.status(200).json(data);

  }).catch((err) => {
    res.status(500).send(error)
  });

});
```
Thanks......
