### ISSUE TITLE
Leagues with more than 50 players

### ISSUE THREAD

**Issue by oysteinwaage** [tgreyuk/fpl-api-node#12]
Hi,
First of all, good work on the API, it works really well!
I've read through your documentation and unless I'm missing something there doesn't seem to be a way to retrieve a complete list of players in a given league if the league contains more than 50 players.
This seems to be the standard page-size FPL uses in their own league views, but is there a possibility for you to extend the API to also accept pageNr (or some other way of getting more than 50 players) by any chance?

Thanks in advance :)

**Comment by tgreyuk** [comment]
Hi,

Thanks for this.

I have released new version 2.2.0 that now takes pageNumber as an additional param.

https://github.com/tgreyuk/fpl-api-node/wiki#findLeagueStandings

The returned data structure contains a 'has_next' flag.

https://github.com/tgreyuk/fpl-api-node/wiki#type_LeagueStandings

Let me know if you require anything else.

Thanks.....
